### ISSUE TITLE
Simulate Y 

### ISSUE THREAD

**Issue by anh-tong** [ryanmccrickerd/rough_bergomi#3]
Hi, 

Thank you for sharing the code.

I wonder why `Y2` has two zeros at the start of the output in this [line.](https://github.com/ryanmccrickerd/rough_bergomi/blob/6a04ca5d2d0f6a45df28ae7bad9c882d537ef14e/rbergomi/rbergomi.py#L61
) I thought it starts with only one zero like `Y1`.

**Comment by ryanmccrickerd** [comment]
Hi,

If you can provide the code, or point me to the notebook, which produces
what you are referring to, I will take a look at this next week.

Otherwise, if I’m not mistaken, we should expect Y2 to start with one zero
like Y1, plus N more zeros where N is the order (kappa) of the hybrid
scheme being used. Since the repo uses kappa=1, then we should see 1+1=2
leading zeros in Y2.

Regards,

**Comment by anh-tong** [comment]
Thank you for replying. 

As I understand, `Y2` aims to compute the second term in the sum (eq 3.4 in the paper https://arxiv.org/pdf/1507.03004.pdf). If we pick the second point (is not affected by the choice of `kappa`) on the discretized grid, the second term does not seem to be zero. 

![image](https://user-images.githubusercontent.com/20637355/165030994-22a62670-e020-45a1-8686-0f240165d5fa.png)

Here is a script to replicate [https://colab.research.google.com/drive/1cwF5u26RB3GApOZg9aX2fg1wEiSQ3qKF?usp=sharing](https://colab.research.google.com/drive/1cwF5u26RB3GApOZg9aX2fg1wEiSQ3qKF?usp=sharing)

**Comment by ryanmccrickerd** [comment]
Thanks for sharing. But Y denotes a _truncated_ Brownian semi-stationary (TBSS) process, so if I'm not mistaken you should be looking at Eq 3.7 in Mikko's paper, not Eq 3.4. 

Y2 then corresponds to the second term in Eq 3.7. Setting kappa=1 there, you see that the first two contributed terms (i=0, i=1) are zero, since the applicable sum runs from k=2 to k=0 then k=2 to k=1. If Y was _just_ a BSS, this would not be the case.

[This paper](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2554754) is required to understand why the relevant process in the risk-neutral rBergomi model is indeed a TBSS, not a BSS. Hope this all helps

**Comment by anh-tong** [comment]
Thank you so much for the suggestion and detailed explanation.
